name: Build and Release Buildroot for Raspberry Pi 400

on:
  push:
    branches:
      - develop
    tags: # Trigger this workflow only when a tag is pushed
      - "v*" # Example: v1.0.0

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      # Step: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Create non existing directories
      - name: Initialize environment
        run: |
          pwd
          mkdir -p ~/work/output/
          set
          tree ~/work

      - name: Create Raspberry Pi image
        uses: aiqs4/rpi-buildroot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_cache_key: buildroot-test-${{ hashFiles('**/config') }}
          build_cache_restore_key: buildroot-test-
          config_file: buildroot_config
          output_path: /home/runner/work/output/sdcard.img
          buildroot_log_path: /home/runner/work/output/buildroot.log

      - name: debug
        run: |
          ls ~
          ls ~/output

      - name: Output buildroot log
        if: always()
        run: |
          cat /home/runner/work/output/buildroot.log

      # Step: Upload only the generated images (and config) to the release
      - name: Upload Buildroot Image to Release
        if: github.ref != 'refs/heads/develop'
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
