name: Build and Release Buildroot for Raspberry Pi 400

on:
  push:
    branches:
      - main
    tags: # Trigger this workflow only when a tag is pushed
      - "v*" # Example: v1.0.0

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      # Step: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Create non existing directories
      - name: Initialize environment
        run: |
          mkdir -p /home/runner/.buildroot-cache
          mkdir -p /home/runner/work/rpi400-buildroot/rpi400-buildroot/output/images
          mkdir -p /home/runner/work/rpi400-buildroot/rpi400-buildroot/dl

      # Step: Set up caching to speed up dependencies and the build process
      - name: Cache CCache
        uses: actions/cache@v3
        with:
          path: /home/runner/.buildroot-cache
          key: buildroot-cc-${{ hashFiles('**/config') }}
          restore-keys: |
            ${{ runner.os }}-buildroot-cc-
            buildroot-cc-

      # Step: Cache the build output for future runs
      - name: Cache Output
        uses: actions/cache@v3
        with:
          path: /home/runner/work/rpi400-buildroot/rpi400-buildroot/output
          key: buildroot-output-${{ hashFiles('**/config') }}
          restore-keys: |
            ${{ runner.os }}-buildroot-output-
            buildroot-output-

      # Step: Cache the build output for future runs
      - name: Cache Downloads
        uses: actions/cache@v3
        with:
          path: /home/runner/work/rpi400-buildroot/rpi400-buildroot/dl
          key: buildroot-dl-${{ hashFiles('**/config') }}
          restore-keys: |
            ${{ runner.os }}-buildroot-dl-
            buildroot-dl-

      # Step: Install dependencies for Buildroot
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libncurses5-dev \
            libssl-dev wget gawk git diffstat unzip texinfo bc

      # Step: Build the image
      - name: Build Buildroot for Raspberry Pi 400
        continue-on-error: true
        run: |
          make -s V=0

      - name: copy config to output
        continue-on-error: true
        run: |
          cp .config /home/runner/work/rpi400-buildroot/rpi400-buildroot/output/images/_config
          pwd
          ls
          echo "===="
          ls /home/runner/work/rpi400-buildroot/rpi400-buildroot

      # Archive build artifacts
      - name: Archive build artifacts
        run: |
          tar -czf release.tar.gz ./output/images/

      # Upload artifact (for later use)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: release.tar.gz

  release:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      # Download artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Fetch all tags
        run: |
          git fetch --tags

      - name: Get the latest tag on the branch
        id: get-latest-tag
        run: |
          # Get the latest tag reachable from the branch
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      # Extract the artifact
      - name: Extract artifact
        run: |
          echo "Extracting artifact..."
          tar -xzf release.tar.gz

      # Verify the contents of the extracted artifact
      - name: List extracted files
        run: |
          echo "Listing extracted files..."
          ls -R output

      # Step: Upload the generated images to the release
      - name: Upload Buildroot Image to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag }}
          files: |
            ./output/images/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
